version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn sats.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - ENV=PRODUCTION
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT={DB_PORT}

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: