# Generated by Django 3.0.4 on 2020-04-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('name', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlotDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecture_type', models.CharField(choices=[(0, 'Lecture'), (1, 'Tutorial')], max_length=1)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Timeslot')),
            ],
        ),
    ]
