# Generated by Django 3.0.4 on 2020-04-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20200406_2312'),
        ('student', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('name', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.Department'),
        ),
        migrations.CreateModel(
            name='TimeSlotDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecture_type', models.CharField(choices=[(0, 'Lecture'), (1, 'Tutorial')], max_length=1)),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTakesCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTakesCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Timeslot'),
        ),
    ]
