# Generated by Django 3.0.4 on 2020-04-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Department'),
        ),
        migrations.AddField(
            model_name='course',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Timeslot'),
        ),
    ]
