# Generated by Django 3.0.4 on 2020-04-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200406_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='studenttakescourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studenttakescourse',
            name='student',
        ),
        migrations.DeleteModel(
            name='FacultyTakesCourse',
        ),
        migrations.DeleteModel(
            name='StudentTakesCourse',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Department'),
        ),
    ]
