# Generated by Django 3.0.4 on 2020-04-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200406_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultytakescourse',
            old_name='Course',
            new_name='course',
        ),
    ]
