# Generated by Django 3.0.4 on 2020-04-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20200407_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultytakescourse',
            old_name='Course',
            new_name='course',
        ),
    ]
