# Generated by Django 3.0.4 on 2020-04-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('course', '0002_auto_20200408_0713'),
        ('attendance', '0002_auto_20200408_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date_time', 'student', 'course')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
    ]
