# Generated by Django 3.0.4 on 2020-04-10 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20200408_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 21, 23, 1, 534123)),
        ),
    ]
