# Generated by Django 3.0.4 on 2020-04-10 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20200410_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 0, 18, 58, 853001)),
        ),
    ]
