# Generated by Django 3.0.4 on 2020-04-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200411_0019'),
        ('attendance', '0005_auto_20200410_1902'),
    ]

    operations = [
    ]
